# Uncomment the next line to define a global platform for your project
platform :osx, "10.13"

target 'Recipe Robot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recipe Robot
  pod 'Sparkle'

  target 'Recipe RobotTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
